{% set name = "napari-sam4is" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e89144279dd9df52583e849079e0da7e42d8a83ec185f66f6bf715144eb41d24


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - magicgui
    - napari
    - numpy
    - python >={{ python_min }}
    - pytorch
    - qtpy
    - scikit-image
    - segment-anything
    - torchvision
    - requests
    - urllib3
    - Pillow

test:
  imports:
    - napari_sam4is
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-SAM4IS
  summary: Create annotations for instance segmentation using Segment Anything models
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/hiroalchem/napari-SAM4IS

extra:
  recipe-maintainers:
    - goanpeca
    - hiroalchem
    - jaimergp
