{% set name = "napari-sam4is" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-SAM4IS-{{ version }}.tar.gz
  sha256: 553823e132a789c62c5e718f1a75858f4935f4ab03a6ff910315529f5a09c9a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - pytorch
    - qtpy
    - scikit-image
    - segment-anything
    - torchvision

test:
  imports:
    - napari_sam4is
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hiroalchem/napari-SAM4IS
  summary: Create annotations for instance segmentation using Segment Anything models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - hiroalchem
    - jaimergp
