{% set name = "napari-sam4is" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 91d189598dd23889de8999603a500a5cda239c8ea8af48aa3c9325ee8fd16089


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - magicgui
    - napari
    - numpy
    - python >={{ python_min }}
    - pytorch
    - qtpy
    - pyyaml
    - scikit-image
    - segment-anything
    - torchvision
    - requests
    - urllib3
    - Pillow
    - platformdirs

test:
  imports:
    - napari_sam4is
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-SAM4IS
  summary: Create annotations for instance segmentation using Segment Anything models
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/hiroalchem/napari-SAM4IS

extra:
  recipe-maintainers:
    - goanpeca
    - hiroalchem
    - jaimergp
