{% set name = "napari-sam4is" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-SAM4IS-{{ version }}.tar.gz
  sha256: 83c6ef4b9af90c3ef1f018713cf116fb6309ca5c81d77fca1e9f68390d5fc6d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - pytorch
    - qtpy
    - scikit-image
    - segment-anything
    - torchvision

test:
  imports:
    - napari_sam4is
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hiroalchem/napari-SAM4IS
  summary: Create annotations for instance segmentation using Segment Anything models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - hiroalchem
    - jaimergp
